spring:
  application:
    name: Cold Email Sender
  profiles:
    active: local
  config:
    import: "classpath:envVariable.properties"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
